apiVersion: v1
kind: Pod
metadata:
  name: test-large
  labels:
    app: test-large
spec:
  containers:
    - name: large
      image: busybox
      command: ["sh", "-c", "echo large pod running; sleep 600"]
      resources:
        requests:
          cpu: "1500m"
          memory: "2Gi"
        limits:
          cpu: "2"
          memory: "3Gi"
